### ISSUE TITLE
Improve toggling of https redirect to work more generally

### ISSUE THREAD

**Issue by WilliamMcCumstie** [openflighthpc/openflight-omnibus-builder#20]
The following line in the `nginx` config will include all the `http` routes within `server-http.d` including all the` http-to-https` redirect paths. However the `https` server is not active by default as it requires a certificate. This opens up the possibility of `502` bad gateway errors instead of a `404`.

The current work around is to append `.disabled` onto the end of https redirects which disables them as well. Then when the `https` server is configured, it will copy (move?) them into place.
`server-http.d/redirect-http-to-https.conf.disabled`
`server-http.d/redirect-http-to-named-https.conf.disabled`

This causes an issue however for plugin web apps such as `flight-desktop-restapi`. Currently they add the configs directly, and will create a `502` error when `https` isn't running.

Instead it would be useful if there was a config and directory tree:
```
# A single enable/disable config that includes the rest
server-http.d/include-redirect-http-to-https.conf.disabled

# A separate directory for the redirect scripts to be dropped in
server-redirect-http-to-https.d/nginx.conf # The base nginx
server-redirect-http-to-https.d/named.conf
server-redirect-http-to-https.d/<custom-app.config>
```

Alternatively setting up one https redirect that works across all applications is an option

**Comment by benarmston** [comment]
As of `flight-www-1.2.0` we have a single redirect which redirects all HTTP traffic to HTTPS once HTTPS is enabled.  As and when use-cases for partially enabling/disabling this redirect arise, we can address them.  See https://trello.com/c/yDasJF2S for more details.
